### ISSUE TITLE
Vanilla k8s: namespace configuration for new users

### ISSUE THREAD

**Issue by lehrig** [lehrig/kubeflow-ppc64le-manifests#4]
For vanilla k8s, trying to run a pipeline causes an error:
```
...
Unauthenticated: Request header error: there is no user identity header
...
```

The root-cause & a fix are well-documented here: https://github.com/kubeflow/pipelines/issues/4440

So, for namespace `kubeflow-user-example-com`, this resolves it:
```
cat << EOF | kubectl apply -f -
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: bind-ml-pipeline-nb-kubeflow-user-example-com
 namespace: kubeflow
spec:
 selector:
   matchLabels:
     app: ml-pipeline
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/kubeflow-user-example-com/sa/default-editor"]
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-header
  namespace: kubeflow-user-example-com
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: ml-pipeline.kubeflow.svc.cluster.local:8888
          route:
            name: default
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: true
          header:
            key: kubeflow-userid
            value: user@example.com
EOF
```

The goal of this issue is to automate this. Options:

1. implement a “create new user” script
2. use the namespace config operator git and build that from source so we can just apply that on vanilla k8s as well, since the CRD “user” should be same for OCP and K8s
